# Usa una imagen base de Node.js
FROM node:18

# Crea y usa el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de dependencias y lo instala
COPY package*.json ./
RUN npm install

# Copia el resto de tu aplicación
COPY . .

# Expone el puerto que usa tu aplicación (ajusta si es necesario)
EXPOSE 3000

# Comando por defecto para iniciar la app
CMD ["npm", "start"]
